name: Custom C++ CI on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the job on a Windows machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest stable version


    - name: Grant execute permissions (if needed)
      run: |
        icacls .\buildn.exe /grant Everyone:F  # Ensure it is executable (optional)

    - name: Compile code using buildn.exe with logging
      run: |
        .\buildn.exe source_file.cpp -o output_file.exe
        echo Build completed with exit code %errorlevel%
        exit /b %errorlevel%



    - name: Run tests
      run: .\output_file.exe  # Run the compiled output to ensure it works correctly
