name: Analyze C++ with eBuildNinja

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the job on a Windows machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest stable version

    - name: Test files for checking errors
      run: |
        g++ src/epi.cpp -lwinmm -lole32 -lgdi32 -lwinspool -lwlanapi -lWs2_32 -lwininet -lwinhttp -liphlpapi -lurlmon -lcomctl32 
