name: Analyze C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Analyze C++ on Windows
      run: |
        .\test
  analyze-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Analyze C++ on Linux
      run: |
        # Install required libraries
        sudo apt install libncurses5-dev libncursesw5-dev
        sudo apt install libcurl4-openssl-dev
        
        # Create output folder
        mkdir linux-target
        
        # Analyze program using g++
        echo "Stared checking files..."
        g++ -Wall -Wextra -pedantic -c src/epi.cpp src/license.cpp src/downloadbar-utils.cpp src/noerrorfile.cpp
  
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Compile for Windows
      run: |
        g++ src/epi.cpp -o epi2.exe -static -lwinmm -lole32 -lgdi32 -lwinspool -lwlanapi -lWs2_32 -lwininet -lwinhttp -liphlpapi -lurlmon -lcomctl32 

    
    - name: Upload executables
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          epi2.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile for Linux
        run: |
          # Install required libraries
          sudo apt install libncurses5-dev libncursesw5-dev
          sudo apt install libcurl4-openssl-dev
          
          # Create output folder
          mkdir linux-target
          
          # Comile program using g++
          g++ src/epi.cpp -o linux-target/epi2 -lncurses -lcurl

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: |
            linux-target/epi2
  
#  build-macos:
#    runs-on: macos-lastest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      
#      - name: Build Program
#        run: |
#          # Install necesary dependencies
#          brew install gcc
#          brew install ncurses curl
#
#          # Create output directories
#          mkdir macos-target
#
#          # Build program
#          g++-13 -o macos-target/epi2 src/epi.cpp -lncurses -lcurl
#      
#      - name: Upload executables
#        uses: actions/upload-artifact@v4
#        with:
#          name: macos-executable
#          path: |
#            macos-target/epi2
