name: Analyze C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enable manual trigger

jobs:
  analyze-win:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Analyze C++
      run: |
        .\test
  
  build-linux:
    runs-on: ubuntu-latest  # Run on a Linux machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  
      - name: Install mingw-w64 for cross-compiling
        run: |
          sudo apt install gcc
          sudo apt install libncurses5-dev libncursesw5-dev
          sudo apt install libcurl4-openssl-dev


      - name: Compile for Linux
        run: |
          g++ src/epi.cpp -o epi2 -lncurses -lcurl

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: |
            epi2

  build-win:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Compile for Windows
      run: |
        g++ src/epi.cpp -o epi2.exe -static -lwinmm -lole32 -lgdi32 -lwinspool -lwlanapi -lWs2_32 -lwininet -lwinhttp -liphlpapi -lurlmon -lcomctl32 

    
    - name: Upload executables
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          epi2.exe