name: Analyze C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Analyze C++ on Windows
      run: |
        .\test
  analyze-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Analyze C++ on Linux
      run: |
        ./test-linux.sh
  
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile for Linux
        run: |
          ./build-linux

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: |
            linux-target/epi2

  build-win:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Compile for Windows
      run: |
        g++ src/epi.cpp -o epi2.exe -static -lwinmm -lole32 -lgdi32 -lwinspool -lwlanapi -lWs2_32 -lwininet -lwinhttp -liphlpapi -lurlmon -lcomctl32 

    
    - name: Upload executables
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          epi2.exe