name: Analyze C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the job on a Windows machine

    steps:
    - name: Test files for checking errors
      run: |
        Start-Process ".\build.bat"
