name: Analyze C++ with eBuildNinja

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the job on a Windows machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest stable version

    - name: Test files for checking errors
      run: |
        .\test
