name: Analyze C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bat:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Clone the repository

    - name: Analyze C++
      run: |
        .\build.bat
